# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'Live Mie' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Live Mie
  pod 'TPKeyboardAvoiding', '~> 1.3'
  pod 'KSToastView', '~> 0.5'
  pod 'BRYXBanner', '~> 0.8'
  pod 'SVProgressHUD'
  
  # Networking
  pod 'Kingfisher', '~> 5.6'
  pod 'Alamofire', '~> 4.5'
  pod 'SwiftyJSON', '~> 5.0'
  pod 'Gloss', '~> 2.0'
  
  # Location
  pod 'INTULocationManager'
#  pod 'HCKalmanFilter'
pod 'Surge', '~> 2.0.0'

  # Logs and Reporting
  pod 'Fabric'
  pod 'Crashlytics'

  #Firebase
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  #pod 'Firebase/Database'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  
  #AR
  pod 'ARCoreLocation', '~> 0.1.8'
  

end
